development:
    access_key_id: AKIAJQOABG5XB23DM4AQ
    secret_access_key: 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
    bucket: design-for-america-development
test:
    access_key_id: AKIAJQOABG5XB23DM4AQ
    secret_access_key: 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
    bucket: design-for-america-test    
production:
    access_key_id: AKIAJQOABG5XB23DM4AQ
    secret_access_key: 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
    bucket: design-for-america-production